### ISSUE TITLE
Documentation create-sample-model.js bug

### ISSUE THREAD

**Issue by kevintechie** [strongloop/loopback-getting-started-intermediate#10]
The create-sample-model.js code in the documentation for this tutorial contains a bug. The computed value for coffeeShopId in the 4th review should be `coffeeShops[2].id`. Currently it is `reviewers[2].id`.

In addition, the unhandled returned err when calling createReviews should be addressed per pull request https://github.com/strongloop/loopback-getting-started-intermediate/pull/9

**Comment by crandmck** [comment]
Thanks for catching that!  I [updated the doc](https://docs.strongloop.com/display/LB/Create+new+models#Createnewmodels-create-sample-models).

We'll review the PR asap.
