### ISSUE TITLE
Update to latest app scaffolding

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-getting-started-intermediate#14]
This app needs to be updated as described in https://github.com/strongloop-internal/scrum-loopback/issues/495.  NOTE: Be sure to recreate all the [tagged releases](https://github.com/strongloop/loopback-getting-started/releases) because they are referenced in the docs.

**Comment by gunjpan** [comment]
Reviewed by @superkhau. LGTH. Merged. Closing.
@crandmck : FYI
