### ISSUE TITLE
currentUser gets wiped on page refresh

### ISSUE THREAD

**Issue by martinjuhasz** [strongloop/loopback-getting-started-intermediate#16]
After logging in and hitting F5 (page refresh) in the browser the rootScope gets wiped and so gets the `currentUser` variable, resulting in the user gets logged out after this. On the other side, the actual User Model from lb-services and the AuthService still have the login Data stored in cookies and `Model.isAuthenticated()` will still return true.

Why are u using the `rootScope` for storing the user when the AuthService is handling this and is there a way to restore it after page refresh?

**Comment by jlister76** [comment]
I had the same questions as martinjuhsz.

**Comment by devotis** [comment]
A PR that attempted to fix is is here: https://github.com/strongloop/loopback-getting-started-intermediate/pull/7/files

Unfortunately it was abandoned and never merged, but it looks promising and straightforward.

**Comment by superkhau** [comment]
Would one of you guys like to take inspiration from it and submit another PR? Unfortunately the other person lost interest (it was almost ready to be merged too after some minor nitpicks!).

**Comment by superkhau** [comment]
Fixed by #27 by @devotis. Closing.
