### ISSUE TITLE
Handshake inactivity timeout

### ISSUE THREAD

**Issue by harshu108** [strongloop/loopback-getting-started-intermediate#18]
{ [Error: Handshake inactivity timeout]
  code: 'PROTOCOL_SEQUENCE_TIMEOUT',
  fatal: true,
  timeout: 10000 }

I get this error when I try to run the app as is.

My PC resides behind secure proxy.

**Comment by richardpringle** [comment]
Hey @harshu108, I unfortunately cannot reproduce this issue and believe that it is not an issue with the example itself. I will close for now, but please re-open the issue and mention me if you believe that there can be a change in the example to get it working for you.

**Comment by KryptKode** [comment]
Having the same issue now. 
@harshu108  Did you find a solution?
