### ISSUE TITLE
ACL typo?

### ISSUE THREAD

**Issue by AnderbergE** [strongloop/loopback-getting-started-intermediate#2]
I tried to translate this example onto my own code. I was unable to call 'create' when $authenticated.
See here: http://docs.strongloop.com/display/public/LB/Define+access+controls

The example says that the file should look like this:
```
...
{
  "accessType": "EXECUTE",
  "principalType": "ROLE",
  "principalId": "$authenticated",
  "permission": "ALLOW",
  "property": "create"
},
...
```
However, I am unable to create anything with this setup. But when I change to accessType "WRITE" it works. Which seems correct according to this page: http://docs.strongloop.com/display/public/LB/Controlling+data+access

**Comment by raymondfeng** [comment]
Can you check which version of `loopback` module using `npm ls`? We fixed a similar issue before.

**Comment by AnderbergE** [comment]
It says: loopback@2.10.0

**Comment by raymondfeng** [comment]
Run `npm up` to make sure loopback@2.11.0.

**Comment by AnderbergE** [comment]
It seems to work with 2.11 :+1: Thanks!
