### ISSUE TITLE
Is it possible to write ES6 in Loopback?

### ISSUE THREAD

**Issue by abimelex** [strongloop/loopback-getting-started-intermediate#23]
I would like to see e.g. this example in ES6 since I couldn't get it to work on my own :( Is that even possible? Do I need to set any flags to run this?

```
module.exports = function(app) {
  // Install a "/ping" route that returns "pong"
  app.get('/ping', function(req, res) {
    res.send('pong');
  });
};
```

Source: https://github.com/strongloop/loopback-getting-started-intermediate/blob/master/server/boot/routes.js

**Comment by superkhau** [comment]
@abimelex No, we do not support ES6 yet. We'll probably have a blog post to announce it when that happens so stay tuned - https://strongloop.com/strongblog/
