### ISSUE TITLE
Client code generation

### ISSUE THREAD

**Issue by adriatic** [strongloop/loopback-getting-started-intermediate#3]
This tutorial introduces the client (Angular) code in a "deus ex machina" fashion (it's just defined in GitHub -- not generated by invocation of a loopback service). So, I am presuming that there is no such service. At the same time, loopback has many nice services on the "server-side", like ```slc loopback:datasource```, ```slc loopback:model``` etc.

I believe that ```slc``` is a domesticated version of yeoman, so adding the support for the "client side" may not be difficult. 

**Note**: I am reporting it here, knowing that this issue belongs somewhere else. However, as I am rewriting the ```loopback-getting-started``` sample from scratch I will have to use something like  https://github.com/DaftMonk/generator-angular-fullstack to get my initial skeleton.

**Comment by pulkitsinghal** [comment]
@adriatic - not sure but just checking in, are you referring to instructions around how the build process generates the `angular loopback services` file?

1. https://github.com/strongloop/grunt-loopback-sdk-angular
2. https://github.com/strongloop/gulp-loopback-sdk-angular

OR perhaps just everything else under the client folder?

**Comment by adriatic** [comment]
@pulkitsinghal: good observation :-) - the samples you referenced illustrate the creation of the Angular $resource file as documented **[here](http://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-GeneratingAngularservices)**.

I am discussing creations of the extended version of the Yeoman generator which will create both server (node) and client (angular) application skeleton.

**Comment by pulkitsinghal** [comment]
@adriatic - Understood! Hope this moves forward.

You may also want to checkout https://gitter.im/loopbackers/loopbackers.github.io which is full of folks that want to create better examples that convert directly into workable projects for loopback users, perhaps striking up a conversation there may lead to more immediate results?

**Comment by crandmck** [comment]
@bajtos I'd like to bring this to your attention.  

If I understand correctly, it's a reasonable suggestion, but (as the OP says) I don't think it really belongs here.  Can you comment or suggest another repo to move this where it will be more likely to receive attention?  Then we can close this issue.

**Comment by adriatic** [comment]
I believe that the improvements could be done in stages and @pulkitsinghal's proposal to see who in https://gitter.im/loopbackers/loopbackers.github.io might be interested to help with this is a good one (for some reason I did not try that chat room yet). Here are the steps that would make the generator a lot better:

1. Add the flag "--supress-user-generation" to [lb-ng](http://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-GeneratingAngularservices) tool. That way I can create the complete server-side CRUD stuff with SLC, "bring in" any Angular client code and roll my own "user/account management" (obviously I want to use Stormpath

2. Gradually augment [Command-line reference (slc loopback)](http://docs.strongloop.com/pages/releaseview.action?pageId=3836281) to include the generation of the client side (Angular initially) all CRUD code that matches the expectations by the server side and output of lb-ng. Since the slc loopback will know a lot about app (like ```loads your LoopBack server application, walks through all models, and generates code registering an AngularJS factory for each model```) there should be a limited amount of additional data that slc would need in addition to what is already defined.

**Comment by bajtos** [comment]
> Add the flag "--supress-user-generation" (...) obviously I want to use Stormpath

I am not familiar with Stormpath, does it require a loopback User model to be present on the server? If you remove the User model from the app or at least make it private (`public:false` in `server/model-config.json`), then `lb-ng` should skip it.

> If I understand correctly, it's a reasonable suggestion, but (as the OP says) I don't think it really belongs here. If you think it makes sense, perhaps the issue should be moved to https://github.com/strongloop/generator-loopback. Then we can close this issue.

+1 for moving the issue to generator-loopback. Related: https://github.com/strongloop/generator-loopback/issues/85

**Comment by adriatic** [comment]
Stormpath does not require loopback User model - it takes over the User management completely (see https://github.com/stormpath/loopback-stormpath for the definition of what the ```loopback-stormpath interface``` will be. Until that interface is not available, I would like to be able to use as much of loopback CRUD related code generation features without possible interference from the User related code. So, making User model private is a perfect solution.

**Comment by crandmck** [comment]
I don't believe that this is an issue with loopback-getting-started-intermediate _per se_, so I'm going to close this issue.  If you still have issues that you want addressed, please open an issue in loopback, or the relevant repo.
