### ISSUE TITLE
Presence of server/boot/root.js here may confuse users.

### ISSUE THREAD

**Issue by dgitsio** [strongloop/loopback-getting-started-intermediate#5]
Feel free to just close this one if I'm off the mark here but since it took me a bit to figure out what was going on I decided to open it.

Although the accompanying tutorial specifies in its [Change or modify the default root route handler](http://docs.strongloop.com/display/public/LB/Add+a+static+web+page#Addastaticwebpage-Changeormodifythedefaultrootroutehandler) section that the user should ```[e]ither delete it or just rename it to something without a .js ending```, the experience of cloning this app and immediately following the instructions in **README.md** may lead the user to think its sole purpose is to show uptime, e.g., ```{"started":"2015-07-06T17:21:02.230Z","uptime":4.614}```.

If the user removes or renames the recently added ```server/boot/root.js``` before running the app, the full functionality is revealed as expected but if the intent is to show the user a finished example of what they will build *before* going through the tutorial, it may make sense to already have ```server/boot/root.js``` renamed or removed.

**Comment by xi3** [comment]
Or the document should be change to visit http://localhost:3000/index.html

**Comment by crandmck** [comment]
@dgitsio You are correct.  I added that file by mistake.  Sorry--my bad.  I just removed it.
Thanks for noticing.
