### ISSUE TITLE
Unable to create relationships in step2

### ISSUE THREAD

**Issue by WillMoreland** [strongloop/loopback-getting-started-intermediate#6]
# I can't create relationships
###### (and not just because I'm a programmer)
If I run
```
$ git clone https://github.com/strongloop/loopback-getting-started-intermediate.git
$ cd loopback-getting-started-intermediate
$ git checkout step2
$ npm install
$ slc loopback:relation
```
I am unable to use the arrow keys to select a model to create a relationship from.

### I'm using...
* Windows 8.1
* Node v0.10.36
* Strongloop v4.0.5

**Comment by WillMoreland** [comment]
Although I had been struggling with this for some time, I solved the problem by using the number keys to select an option. This then re-activated the arrow keys somehow.

**Comment by pulkitsinghal** [comment]
@WillMoreland - May I recommend using https://koding.com/ as your dev platform of choice while working with loopback? This is just so you face less blockers both now and in the future, that's all. I've got nothing against you finding the right tooling for your windows env. Best of luck!

It will also make it easier for you to share your project when asking for help and collaboration. There 1 GB free plan is quite nice for learning and some pre-prod development too.

**Comment by jakerella** [comment]
@WillMoreland I hate to day it, but this one might just be you. I've tried to replicate on Windows 8.1 with Node v0.10.36 and v0.12.0 with no success. I've tried in the plain command prompt and in Powershell. Everything works as expected.

Which terminal are you using? Can you run any other slc commands that use the menus? (`slc loopback:model` for example)

**Comment by rmg** [comment]
@WillMoreland your console examples suggest bash.. do you happen to be using Cygwin? If so, that would be a problem.

**Comment by superkhau** [comment]
@WillMoreland Are you still running into issues? Can I close this?

**Comment by WillMoreland** [comment]
@superkhau I think it was cmd.exe being crappy. I actually ended up using Ubuntu. Either way I don't think it's really a problem with the software. I'd go ahead and close the issue.

**Comment by superkhau** [comment]
Sounds good, ty.

**Comment by doktordirk** [comment]
i'm having the same issue. not extremly consistent though. unfortunatelly i've no idea yet what might influence it

*win8.1
*console and powershell
*strongloop v5.0.1 (node v4.2.2)
├── strong-arc@1.8.4 (b7b568d)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

i've seen/having similar issues with yo.

**Comment by superkhau** [comment]
@doktordirk Please create your own issue. Do not reuse a closed issue.
