### ISSUE TITLE
Extends Users to MyAppUser instead of Reviewer

### ISSUE THREAD

**Issue by PhilippeCorreges** [strongloop/loopback-getting-started-intermediate#8]
Hello,
I try to change reviewer class to another class name that best fits my app.
I create the model, regenerate lb-services and change 
.factory('AuthService', ['Reviewer', '$q', '$rootScope', function(User, $q,

by.

factory('AuthService', ['MyAppUser', '$q', '$rootScope', function(User, $q,

I did not find any other occurence of Reviewer in any source file. So I am a little upset.
Is this something I did wrong or an issue ? I do not see why an issue.

Thanks

**Comment by pulkitsinghal** [comment]
@PhilippeCorreges - What happened after your change? What broke?

**Comment by PhilippeCorreges** [comment]
Hi Pulkit
I modified the following code :
angular
  .module('app')
  .factory('AuthService', ['applicationUser', '$q', '$rootScope', function(User, $q,
      $rootScope) {
    function login(email, password) {
      return User
        .login({email: email, password: password})
        .$promise
        .then(function(response) {
          $rootScope.currentUser = {
            id: response.user.id,
            tokenId: response.id,
            email: email
          };
        });
    }

    function logout() {
      return User
       .logout()
       .$promise
       .then(function() {
         $rootScope.currentUser = null;
       });
    }

    function register(email, password) {
      return User
        .create({
         email: email,
         password: password
       })
       .$promise;
    }

    return {
      login: login,
      logout: logout,
      register: register
    };
  }]);
creating a factory for « applicationUser ».

I created applicationUser.json and applicationUser.js the same as reviewer’s.
I generated again lb-services.
I set the datasource for this model to the same as reviewer (i.e. MongoDB).
I cannot register anymore.

I do not understand why as there is only one occurence of Reviewer in the code …

thanks for your help

Philippe

**Comment by pulkitsinghal** [comment]
Could it be the naming of the files? I wonder if they are supposed to follow a specific naming convention: `application-user.json` and `application-user.js` ... I would be willing to have a screenshare session with you, you can ping me privately over chat here: https://gitter.im/pulkitsinghal and we can schedule something

**Comment by PhilippeCorreges** [comment]
Hi Pulkit,
thanks for you interest.
The problem was linked ti naming convention and lb-services not generated in the correct folder. I had TWO files so no alert launched :-)
It was obvious for me that was not so tricky but was a little lost.

Thanks for your time.

**Comment by crandmck** [comment]
Is there something here that we need to cover in docs?  Dan we close this issue now?

**Comment by PhilippeCorreges** [comment]
Hi Rand
Maybe there is it precise that after the extend, or any model modif, lb services has to be generated.
That was not very clear to me. I may be not the best sample :)

Philippe

**Comment by crandmck** [comment]
Thanks, I added a note to https://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-GeneratingAngularservices to clarify that you need to re-run the tool whenever you modify your models.

**Comment by PhilippeCorreges** [comment]
Great!
